server:
  port: 18099

spring:
  application:
    name: mall-ai
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  config:
    import:
      - nacos:mall-ai.yaml